server:
  port: 6001
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka01
    prefer-ip-address: true
  server:
    eviction-interval-timer-in-ms: 30000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:6001/eureka/
