server:
  port: 6005
spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gaoliqing/cloud-config.git
          username: gaoliqing4832@163.com
          password: gaoliqing1831
          search-paths: /cloud-config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/